name: Build APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Installing Cordova!"
        npm i cordova@10.0.0 -g
        echo "Installing the npm dependencies!"
        cd testapp
        npm i
        echo "Copying nodejs-mobile-cordova plugin"
        npm run copy-module
        echo "Preparing the Android project"
        cordova prepare android
        echo "Building the Android project"
        cordova build android
